services:
  db:
    container_name: my-cash-flow-pg
    image: bitnami/postgresql
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/bitnami/postgresql

volumes:
  db_data:
    driver: local